version: "3.9"

networks:
  laravel_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    depends_on:
      - db
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    networks:
      - laravel_network
    entrypoint: ["/entrypoint-app.sh"]
    restart: always

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_queue
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    networks:
      - laravel_network
    entrypoint: ["/entrypoint-queue.sh"]
    restart: always

  db:
    image: mariadb:11.4
    container_name: laravel_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel_network
